default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample-app-taskleaf_development

test:
  <<: *default
  database: sample-app-taskleaf_test

production:
  <<: *default
  database: sample-app-taskleaf_production
  username: sample-app-taskleaf
  password: <%= ENV['SAMPLE_APP_TASKLEAF_DATABASE_PASSWORD'] %>
